commands:
  company_search:
    queries:
    - emp_limit_2
    - emp_limit
    - employees
    - employees_network
    query_order: employees_network, employees, emp_limit_2, emp_limit
  emp_search:
    queries:
    - employees
    - emp_limit
    query_order: employees, emp_limit
  test_command:
    queries:
    - emp_limit_2
    - employees_network
    - emp_limit
    query_order: emp_limit_2, employees_network, emp_limit
  test_one:
    queries:
    - employees
    - emp_limit_2_network
    - emp_limit_2
    query_order: employees, emp_limit_2_network, emp_limit_2
  test_two:
    queries:
    - emp_search
    - emp_limit
    query_order: emp_limit, emp_search
connections:
  an_azure_server:
    database: db_name
    password: ''
    server: server_name
    type: azure
    username: username
  company:
    database: RealParsmodel
    password: ''
    server: localhost
    type: mysql
    username: root
  mysql:
    database: test_db
    password: ''
    server: localhost
    type: mysql
    username: root
queries:
  emp_limit:
    connection: mysql
    query: SELECT id, name, email_address FROM users LIMIT 1
  emp_limit_2:
    connection: mysql
    query: SELECT * FROM users LIMIT 2
  emp_search:
    connection: mysql
    query: "SELECT id,\r\n       name,\r\n       email_address\r\nFROM users\r\nWHERE name LIKE &p"
  employees:
    connection: company
    query: SELECT employeeNumber, lastName, firstName, extension, email, officeCode, reportsTo, jobTitle FROM employees ORDER BY firstName ASC
settings:
  additional_config: ""
  auto_format_queries: false
  better_tables: false
  settings: false
  two_columns: false
